import { z } from 'zod';

// Common schemas
export const PaginationSchema = z.object({
  page: z.string().optional().transform(val => val ? parseInt(val) : 1),
  limit: z.string().optional().transform(val => val ? parseInt(val) : 10),
  sortBy: z.string().optional(),
  sortOrder: z.enum(['asc', 'desc']).optional().default('desc'),
});

export const IdParamSchema = z.object({
  id: z.string().transform(val => parseInt(val)),
});

// Auth schemas
export const RegisterSchema = z.object({
  name: z.string().min(2, 'Name must be at least 2 characters'),
  email: z.string().email('Invalid email address'),
  password: z.string().min(6, 'Password must be at least 6 characters'),
  role: z.enum(['USER', 'ADMIN', 'SUPERVISOR', 'FINANCE', 'CONSTRUCTION']).optional(),
});

export const LoginSchema = z.object({
  email: z.string().email('Invalid email address'),
  password: z.string().min(1, 'Password is required'),
});

// Project schemas
export const ProjectCreateSchema = z.object({
  Name: z.string().min(1, 'Name is required'),
  StartDate: z.string().datetime('Invalid date format'),
  EndDate: z.string().datetime('Invalid date format').optional(),
  TotalBudget: z.number().positive('Total budget must be positive'),
});

export const ProjectUpdateSchema = z.object({
  Name: z.string().min(1, 'Name is required').optional(),
  StartDate: z.string().datetime('Invalid date format').optional(),
  EndDate: z.string().datetime('Invalid date format').optional(),
  TotalBudget: z.number().positive('Total budget must be positive').optional(),
});

export const ProjectParamsSchema = z.object({
  id: z.string().transform(val => parseInt(val)),
});

// Task schemas
export const TaskCreateSchema = z.object({
  Description: z.string().min(1, 'Description is required'),
  Duration: z.number().positive('Duration must be positive').optional(),
  AssignedTo: z.string().optional(),
  CompletionStatus: z.enum(['NotStarted', 'InProgress', 'Completed']).optional(),
});

export const TaskUpdateSchema = z.object({
  Description: z.string().min(1, 'Description is required').optional(),
  Duration: z.number().positive('Duration must be positive').optional(),
  AssignedTo: z.string().optional(),
  CompletionStatus: z.enum(['NotStarted', 'InProgress', 'Completed']).optional(),
});

export const TaskParamsSchema = z.object({
  id: z.string().transform(val => parseInt(val)),
  projectId: z.string().transform(val => parseInt(val)).optional(),
});

// Resource schemas
export const ResourceCreateSchema = z.object({
  Type: z.string().min(1, 'Type is required'),
  Quantity: z.number().positive('Quantity must be positive'),
});

export const ResourceUpdateSchema = z.object({
  Type: z.string().min(1, 'Type is required').optional(),
  Quantity: z.number().positive('Quantity must be positive').optional(),
});

export const ResourceParamsSchema = z.object({
  id: z.string().transform(val => parseInt(val)),
});

// Expense schemas
export const ExpenseCreateSchema = z.object({
  Description: z.string().optional(),
  Cost: z.number().positive('Cost must be positive'),
  Date: z.string().datetime('Invalid date format'),
});

export const ExpenseUpdateSchema = z.object({
  Description: z.string().optional(),
  Cost: z.number().positive('Cost must be positive').optional(),
  Date: z.string().datetime('Invalid date format').optional(),
});

export const ExpenseParamsSchema = z.object({
  id: z.string().transform(val => parseInt(val)),
  taskId: z.string().transform(val => parseInt(val)).optional(),
});

// Measurement schemas
export const MeasurementCreateSchema = z.object({
  SiteID: z.string().min(1, 'Site ID is required'),
  MeasurementType: z.string().min(1, 'Measurement type is required'),
  Value: z.number(),
  Date: z.string().datetime('Invalid date format'),
});

export const MeasurementUpdateSchema = z.object({
  SiteID: z.string().min(1, 'Site ID is required').optional(),
  MeasurementType: z.string().min(1, 'Measurement type is required').optional(),
  Value: z.number().optional(),
  Date: z.string().datetime('Invalid date format').optional(),
});

export const MeasurementParamsSchema = z.object({
  id: z.string().transform(val => parseInt(val)),
  taskId: z.string().transform(val => parseInt(val)).optional(),
});

// Validation schemas
export const ValidationCreateSchema = z.object({
  SiteID: z.string().min(1, 'Site ID is required'),
  Status: z.enum(['Pending', 'Approved', 'Rejected']).optional(),
  Notes: z.string().optional(),
  GeneratedBy: z.string().min(1, 'Generated by is required'),
});

export const ValidationUpdateSchema = z.object({
  SiteID: z.string().min(1, 'Site ID is required').optional(),
  Status: z.enum(['Pending', 'Approved', 'Rejected']).optional(),
  Notes: z.string().optional(),
  GeneratedBy: z.string().min(1, 'Generated by is required').optional(),
});

export const ValidationParamsSchema = z.object({
  id: z.string().transform(val => parseInt(val)),
  taskId: z.string().transform(val => parseInt(val)).optional(),
});

// Report schemas
export const ReportCreateSchema = z.object({
  ValidationID: z.number().positive('Validation ID must be positive'),
  ProjectID: z.number().positive('Project ID must be positive'),
  GeneratedBy: z.string().min(1, 'Generated by is required'),
});

export const ReportParamsSchema = z.object({
  id: z.string().transform(val => parseInt(val)),
});

// ProjectResource schemas
export const ProjectResourceCreateSchema = z.object({
  ProjectID: z.number().positive('Project ID must be positive'),
  ResourceID: z.number().positive('Resource ID must be positive'),
});

export const ProjectResourceParamsSchema = z.object({
  projectId: z.string().transform(val => parseInt(val)),
  resourceId: z.string().transform(val => parseInt(val)),
});

// TaskResource schemas
export const TaskResourceCreateSchema = z.object({
  TaskID: z.number().positive('Task ID must be positive'),
  ResourceID: z.number().positive('Resource ID must be positive'),
});

export const TaskResourceParamsSchema = z.object({
  taskId: z.string().transform(val => parseInt(val)),
  resourceId: z.string().transform(val => parseInt(val)),
});

// Schema type exports for TypeScript inference
export type PaginationParams = z.infer<typeof PaginationSchema>;
export type RegisterRequest = z.infer<typeof RegisterSchema>;
export type LoginRequest = z.infer<typeof LoginSchema>;
export type ProjectCreateRequest = z.infer<typeof ProjectCreateSchema>;
export type ProjectUpdateRequest = z.infer<typeof ProjectUpdateSchema>;
export type TaskCreateRequest = z.infer<typeof TaskCreateSchema>;
export type TaskUpdateRequest = z.infer<typeof TaskUpdateSchema>;
export type ResourceCreateRequest = z.infer<typeof ResourceCreateSchema>;
export type ResourceUpdateRequest = z.infer<typeof ResourceUpdateSchema>;
export type ExpenseCreateRequest = z.infer<typeof ExpenseCreateSchema>;
export type ExpenseUpdateRequest = z.infer<typeof ExpenseUpdateSchema>;
export type MeasurementCreateRequest = z.infer<typeof MeasurementCreateSchema>;
export type MeasurementUpdateRequest = z.infer<typeof MeasurementUpdateSchema>;
export type ValidationCreateRequest = z.infer<typeof ValidationCreateSchema>;
export type ValidationUpdateRequest = z.infer<typeof ValidationUpdateSchema>;
export type ReportCreateRequest = z.infer<typeof ReportCreateSchema>;
export type ProjectResourceCreateRequest = z.infer<typeof ProjectResourceCreateSchema>;
export type TaskResourceCreateRequest = z.infer<typeof TaskResourceCreateSchema>;
